//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySuaChuaXe_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomTho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhomTho()
        {
            this.Thoes = new HashSet<Tho>();
        }
    
        public string ID_NhomTho { get; set; }
        public string Ten_NhomTho { get; set; }
        public string ID_TruongNhom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tho> Thoes { get; set; }
    }
}
