//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySuaChuaXe_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public string ID_PhieuThu { get; set; }
        public string HoTenNguoiThu_PhieuThu { get; set; }
        public string HoTenNguoiNop_PhieuThu { get; set; }
        public Nullable<System.DateTime> NgayThu_PhieuThu { get; set; }
        public Nullable<double> SoTienThu_PhieuThu { get; set; }
        public string ID_HopDong { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
