//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySuaChuaXe_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tho()
        {
            this.ChiTietHopDongs = new HashSet<ChiTietHopDong>();
            this.CongViecs = new HashSet<CongViec>();
        }
    
        public string ID_Tho { get; set; }
        public string HoTen_Tho { get; set; }
        public Nullable<bool> GioiTinh_Tho { get; set; }
        public Nullable<System.DateTime> NgaySinh_Tho { get; set; }
        public string DiaChi_Tho { get; set; }
        public Nullable<double> Luong_Tho { get; set; }
        public string ID_NhomTho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHopDong> ChiTietHopDongs { get; set; }
        public virtual NhomTho NhomTho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
    }
}
